version: '3.8'

services:
  producer-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PG_URL=postgresql://admin:secret@db:5432/mydatabase?sslmode=disable
      - RMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.12-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

volumes:
  postgres_data:
