server:
  name: "indexer-core"
  version: "0.0.1"
  stage: "dev"

http:
  port: "9090"

logger:
  file: "indexer-core"

rabbitmq:
  rpc_server_exchange: "rpc_server"
  rpc_client_exchange: "rpc_client"