server:
  name: "block-producer"
  version: "0.0.1"
  stage: "dev"
  worker_count: 1
  block_start_number: 17423949
  core_service_url: "localhost:9090"

http:
  port: "8080"

logger:
  file: "producer"

rabbitmq:
  rpc_server_exchange: "rpc_server"
  rpc_client_exchange: "rpc_client"

eth_node:
  network_type: "sepolia"
  trace_enabled: false