server:
  name: "block-producer"
  version: "0.0.1"
  stage: "prod"
  worker_count: 5

http:
  port: "8080"

logger:
  file: "app.log"

rabbitmq:
  rpc_server_exchange: "rpc_server"
  rpc_client_exchange: "rpc_client"

eth_node:
  network_type: "sepolia"