apiVersion: v1
kind: Service
metadata:
  name: indexer-explorer
spec:
  type: NodePort
  selector:
    app: indexer-explorer
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30083
